// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  "apiKey": "AIzaSyB5xgeYSJTVz6Jm-LTKfYYWYdMYBi3CjQI",
  "authDomain": "studio-4318947832-29d6b.firebaseapp.com",
  "projectId": "studio-4318947832-29d6b",
  "storageBucket": "studio-4318947832-29d6b.firebasestorage.app",
  "messagingSenderId": "21690230222",
  "appId": "1:21690230222:web:c884b5f01fb8ebebf8379f",
  "measurementId": "G-KJPW35C21C"
};
